### ISSUE TITLE
RFC: optimizations

### ISSUE THREAD

**Issue by simon-weber** [eventbrite/nose-knows#2]
I've been playing around with setting up knows at Venmo. One of the blockers was speed: knows more than doubled our build time.

I took at stab at optimizing it and managed to reduce the overhead by ~80%, albeit with some breaking changes. The biggest win, though - switching to setprofile - should be backwards compatible (I think, at least; I didn't test it with multiple threads).

I figured I'd open an issue rather than a PR to get your thoughts on what you'd be interested in merging. Here are the changes: https://github.com/eventbrite/nose-knows/compare/master...venmo:sw_optimize.

**Comment by eyalr** [comment]
One of the directions I was considering going with this was specificity. Currently, it does a mapping of file => tests, but in the future the current methodology could theoretically support a line_in_file => tests. I think that there's definitely room for a --quick flag, perhaps? Overall this looks great though, please issue a PR!
